version: 2.1

jobs:
  build:
    docker:
      - image: python:buster
    steps:
      - checkout
      - run: 
          name: tox-test mailadm 
          environment: 
                LC_ALL: C.UTF-8
                LANG: C.UTF-8
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install .
            pip install tox
            tox 
